USE MATERIALTEC;

CREATE TABLE ROL(
ID      INT NOT NULL,
NAME  VARCHAR(50) NOT NULL,
PRIMARY KEY (ID)
);


CREATE TABLE USUARIO(
    ID INT NOT NULL IDENTITY,
    USERNAME NVARCHAR(100) NOT NULL,
    NOMBRE NVARCHAR(100) NOT NULL,
    APELLIDO NVARCHAR(100) NOT NULL,
    PASSWORD NVARCHAR(255) NOT NULL,
    TEL INT NOT NULL,
    EMAIL NVARCHAR(255),
    ACTIVO int NOT NULL DEFAULT 0,
    FK_ID_ROLE int NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID), 
    FOREIGN KEY (FK_ID_ROLE) REFERENCES ROL(ID)
	
	
);


CREATE TABLE CATEGORIA
(
    ID INT NOT NULL IDENTITY,
    NOMBRE NVARCHAR(50),
    ACTIVO INT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,

	PRIMARY KEY(ID) 
   
);


CREATE TABLE ALMACEN
(
    ID INT NOT NULL IDENTITY,
    NOMBRE NVARCHAR(100) NOT NULL,
    CAPACIDAD INT NULL,
    CREATED_AT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID) 
);


CREATE TABLE PRODUCTO
(
    ID INT NOT NULL IDENTITY,
    NOMBRE NVARCHAR(100),
    DESCRIPCION TEXT,
    CANTIDAD INT,
    PRECIO FLOAT,
    PUNTO_REORDEN INT,
    GARANTIA DATE,
    TIENDA INT,
    AUTORIZADO INT DEFAULT 0,
    COSTO FLOAT,
    COMPRADO INT DEFAULT 0,
    DESCUENTO INT DEFAULT 0,
    FK_CATEGORIA INT NOT NULL,
    FK_ALMACEN INT NOT NULL,
    ACTIVO INT NOT NULL DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_CATEGORIA) REFERENCES CATEGORIA (ID),
    FOREIGN KEY (FK_ALMACEN) REFERENCES ALMACEN (ID)
);


CREATE TABLE METODO_PAGO
(
    ID INT NOT NULL IDENTITY,
    NOMBRE      NVARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE DIRECCION
(
    ID INT NOT NULL IDENTITY,
    ESTADO NVARCHAR(50) NOT NULL,
    CIUDAD NVARCHAR(50) NOT NULL,
    MUNICIPIO NVARCHAR(50) NOT NULL,
    COLONIA NVARCHAR(100) NOT NULL,
    CALLE NVARCHAR(100) NOT NULL,
    CP NVARCHAR(8) NOT NULL,
    NUMERO NVARCHAR(10) NOT NULL,
    ACTIVO INT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FK_CLIENTE INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_CLIENTE) REFERENCES USUARIO(ID)
);


CREATE TABLE ORDEN
(
    ID INT NOT NULL IDENTITY,
    TOTAL FLOAT NOT NULL,
    SUBTOTAL    FLOAT NOT NULL,
    PAGADO      INT DEFAULT 0,
    DESCUENTO   FLOAT DEFAULT 0,
    NUMERO_GUIA NVARCHAR(100) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FK_CLIENT INT NOT NULL,
	FK_METODO_PAGO INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_CLIENT) REFERENCES USUARIO(ID),
    FOREIGN KEY (FK_METODO_PAGO) REFERENCES METODO_PAGO (ID)
);


CREATE TABLE ORDEN_PRODUCTO
(
    ID INT NOT NULL IDENTITY,
    PRECIO FLOAT NOT NULL,
    CANTIDAD    INT NOT NULL, 
	FK_PRODUCTO INT NOT NULL,
	FK_ORDEN    INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_PRODUCTO) REFERENCES PRODUCTO (ID),
    FOREIGN KEY (FK_ORDEN) REFERENCES ORDEN (ID)
);


CREATE TABLE IMAGEN_PRODUCTO
(
    ID INT NOT NULL IDENTITY,
    IMAGEN      NVARCHAR(100),
    PRINCIPAL   INT NOT NULL DEFAULT 0,
    FK_PRODUCTO INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_PRODUCTO) REFERENCES PRODUCTO (ID)
);


CREATE TABLE PROMOCION
(
    ID INT NOT NULL IDENTITY,
    TITULO      NVARCHAR(100) NOT NULL,
    DESCRIPCION NVARCHAR(100) NOT NULL,
    AUTORIZADO  INT DEFAULT 0,
    FECHA_INICIAL DATE NOT NULL,
    FECHA_FINAL DATE NOT NULL,
    ACTIVO      INT DEFAULT 0,
	PRIMARY KEY (ID)
);


CREATE TABLE TIPO_PROMOCION
(
    ID INT NOT NULL IDENTITY,
    NOMBRE      NVARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTO_PROMOCION
(
    ID INT NOT NULL IDENTITY,
    DESCUENTO   INT NOT NULL,
    PLUS        INT NOT NULL,
    ACTIVE      INT DEFAULT 0,
    CREATED_AT  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FK_TIPO_PROMOCION INT NOT NULL,
	FK_PROMOCION INT NOT NULL,
	FK_PRODUCTO INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_TIPO_PROMOCION) REFERENCES TIPO_PROMOCION (ID),
    FOREIGN KEY (FK_PROMOCION) REFERENCES PROMOCION (ID),
    FOREIGN KEY (FK_PRODUCTO) REFERENCES PRODUCTO (ID)
);

CREATE TABLE PROVEEDOR
(
    ID INT NOT NULL IDENTITY,
    NOMBRE      NVARCHAR(100) NOT NULL,
    RFC         NVARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
);



CREATE TABLE PEDIDO_PROVEEDOR
(
    ID INT NOT NULL IDENTITY,
    PRECIO_TOTAL FLOAT NOT NULL,
    PAGADO      INT DEFAULT 0,
    AUTORIZADO  INT DEFAULT 0,
    FECHA       DATE NOT NULL,
    ACTIVO      INT DEFAULT 1,
    CRATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FK_PROVEEDOR INT NOT NULL,
	FK_USUARIO  INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_PROVEEDOR) REFERENCES PROVEEDOR (ID),
    FOREIGN KEY (FK_USUARIO) REFERENCES USUARIO (ID)
);


CREATE TABLE FACTURA
(
    ID INT NOT NULL IDENTITY,
    PAGO_TOTAL  FLOAT NOT NULL,
    FECHA_PAGO  DATE NOT NULL,
    CRATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FK_PEDIDO_PROVEEDOR INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_PEDIDO_PROVEEDOR) REFERENCES PEDIDO_PROVEEDOR (ID)
);

CREATE TABLE FACTURA_PRODUCTO
(
    ID INT NOT NULL IDENTITY,
    CRATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FK_FACTURA  INT NOT NULL,
	FK_PRODUCTO INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_FACTURA) REFERENCES FACTURA (ID),
    FOREIGN KEY (FK_PRODUCTO) REFERENCES PRODUCTO (ID)

);

CREATE TABLE PRODUCTO_PROVEEDOR
(
    ID INT NOT NULL IDENTITY,
    NOMBRE      NVARCHAR(100) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PRECIO      FLOAT NOT NULL,
    GARANTIA    INT DEFAULT 30,
    CRATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)

);

CREATE TABLE PRODUCTO_PEDIDO
(
    ID INT NOT NULL IDENTITY,
    CANTIDAD    INT NOT NULL,
    COSTO       FLOAT NOT NULL,
    CRATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FK_PRODUCTO_PROVEEDOR INT NOT NULL,
	FK_PEDIDO_PROVEEDOR INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_PRODUCTO_PROVEEDOR) REFERENCES PRODUCTO_PROVEEDOR (ID),
    FOREIGN KEY (FK_PEDIDO_PROVEEDOR) REFERENCES PEDIDO_PROVEEDOR (ID)

);

CREATE TABLE DEVOLUCION_PEDIDO
(
    ID          INT NOT NULL IDENTITY,
    CANTIDAD    INT NOT NULL,
    RAZON       NVARCHAR(100) NOT NULL,
    CRATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FK_PEDIDO_PROVEEDOR INT NOT NULL,
	FK_PRODUCTO_PEDIDO INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_PEDIDO_PROVEEDOR) REFERENCES PEDIDO_PROVEEDOR (ID),
    FOREIGN KEY (FK_PRODUCTO_PEDIDO) REFERENCES PRODUCTO_PEDIDO (ID)
);

CREATE TABLE AGENTE_VENTA
(
    ID          INT NOT NULL IDENTITY,
    CRATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (ID)
);

CREATE TABLE CHAT
(
    ID          INT NOT NULL IDENTITY,
    MENSAJE     NVARCHAR(100),
	FK_DESTINATARIO INT NOT NULL,
	FK_REMITENTE INT NOT NULL,
	PRIMARY KEY (ID),
    FOREIGN KEY (FK_DESTINATARIO) REFERENCES USUARIO(ID),
    FOREIGN KEY (FK_REMITENTE) REFERENCES USUARIO(ID)
);

