//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialTec.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MATERIALTECEntities : DbContext
    {
        public MATERIALTECEntities()
            : base("name=MATERIALTECEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AGENTE_VENTA> AGENTE_VENTA { get; set; }
        public DbSet<ALMACEN> ALMACENs { get; set; }
        public DbSet<CATEGORIA> CATEGORIAs { get; set; }
        public DbSet<CHAT> CHATs { get; set; }
        public DbSet<DEVOLUCION_PEDIDO> DEVOLUCION_PEDIDO { get; set; }
        public DbSet<DIRECCION> DIRECCIONs { get; set; }
        public DbSet<FACTURA> FACTURAs { get; set; }
        public DbSet<FACTURA_PRODUCTO> FACTURA_PRODUCTO { get; set; }
        public DbSet<IMAGEN_PRODUCTO> IMAGEN_PRODUCTO { get; set; }
        public DbSet<METODO_PAGO> METODO_PAGO { get; set; }
        public DbSet<ORDEN> ORDENs { get; set; }
        public DbSet<ORDEN_PRODUCTO> ORDEN_PRODUCTO { get; set; }
        public DbSet<PEDIDO_PROVEEDOR> PEDIDO_PROVEEDOR { get; set; }
        public DbSet<PRODUCTO> PRODUCTOes { get; set; }
        public DbSet<PRODUCTO_PEDIDO> PRODUCTO_PEDIDO { get; set; }
        public DbSet<PRODUCTO_PROMOCION> PRODUCTO_PROMOCION { get; set; }
        public DbSet<PRODUCTO_PROVEEDOR> PRODUCTO_PROVEEDOR { get; set; }
        public DbSet<PROMOCION> PROMOCIONs { get; set; }
        public DbSet<PROVEEDOR> PROVEEDORs { get; set; }
        public DbSet<ROL> ROLs { get; set; }
        public DbSet<TIPO_PROMOCION> TIPO_PROMOCION { get; set; }
        public DbSet<USUARIO> USUARIOs { get; set; }
    }
}
