//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialTec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO_PROVEEDOR
    {
        public PEDIDO_PROVEEDOR()
        {
            this.DEVOLUCION_PEDIDO = new HashSet<DEVOLUCION_PEDIDO>();
            this.FACTURAs = new HashSet<FACTURA>();
            this.PRODUCTO_PEDIDO = new HashSet<PRODUCTO_PEDIDO>();
        }
    
        public int ID { get; set; }
        public double PRECIO_TOTAL { get; set; }
        public Nullable<int> PAGADO { get; set; }
        public Nullable<int> AUTORIZADO { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<int> ACTIVO { get; set; }
        public System.DateTime CRATED_AT { get; set; }
        public int FK_PROVEEDOR { get; set; }
        public int FK_USUARIO { get; set; }
    
        public virtual ICollection<DEVOLUCION_PEDIDO> DEVOLUCION_PEDIDO { get; set; }
        public virtual ICollection<FACTURA> FACTURAs { get; set; }
        public virtual PROVEEDOR PROVEEDOR { get; set; }
        public virtual USUARIO USUARIO { get; set; }
        public virtual ICollection<PRODUCTO_PEDIDO> PRODUCTO_PEDIDO { get; set; }
    }
}
