//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialTec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO_PEDIDO
    {
        public PRODUCTO_PEDIDO()
        {
            this.DEVOLUCION_PEDIDO = new HashSet<DEVOLUCION_PEDIDO>();
        }
    
        public int ID { get; set; }
        public int CANTIDAD { get; set; }
        public double COSTO { get; set; }
        public System.DateTime CRATED_AT { get; set; }
        public int FK_PRODUCTO_PROVEEDOR { get; set; }
        public int FK_PEDIDO_PROVEEDOR { get; set; }
    
        public virtual ICollection<DEVOLUCION_PEDIDO> DEVOLUCION_PEDIDO { get; set; }
        public virtual PEDIDO_PROVEEDOR PEDIDO_PROVEEDOR { get; set; }
        public virtual PRODUCTO_PROVEEDOR PRODUCTO_PROVEEDOR { get; set; }
    }
}
